### ISSUE TITLE
Demo website not working

### ISSUE THREAD

**Issue by remissao** [m-elewa/freelancers-market#11]
The  Demo website is not working anymore.

@dsun9 you can see the demo website that hosted on Azure here http://freelancers-market.ml/

_Originally posted by @m-elewa in https://github.com/m-elewa/freelancers-market/issues/3#issuecomment-626246839_

**Comment by m-elewa** [comment]
@remissao the server is expired, I'll run the website on another server soon.

**Comment by remissao** [comment]
> @remissao the server is expired, I'll run the website on another server soon.

Thanks!
