### ISSUE TITLE
UnexpectedValueException

### ISSUE THREAD

**Issue by ghost** [m-elewa/freelancers-market#14]
I tried to setup using Docker (as per given instructions in give README file).
But after opening url https://165.22.219.198/
it give error: "UnexpectedValueException
The stream or file "/var/www/storage/logs/laravel-2020-07-21.log" could not be opened: failed to open stream: Permission denied " 
Attached Scree-shot of the same.
![Screenshot from 2020-07-21 17-03-06](https://user-images.githubusercontent.com/37117700/88050294-2c69d680-cb74-11ea-898e-78e44a1855e5.png)

**Comment by m-elewa** [comment]
@Akshay-Wagh please refer to this issue #13 

> sudo apt update && sudo apt -y upgrade
> sudo apt install make -y
> 
> sudo add-apt-repository ppa:git-core/ppa -y
> 
> sudo apt-get -y install \
> apt-transport-https \
> ca-certificates \
> curl \
> gnupg-agent \
> software-properties-common \
> docker-compose \
> virtualbox
> 
> curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
> 
> sudo add-apt-repository \
> "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
> $(lsb_release -cs) \
> stable"
> 
> sudo apt-get -y install docker-ce docker-ce-cli containerd.io
> 
> sudo usermod -aG docker ${USER}



and let me know if you still facing the same error

**Comment by ghost** [comment]
Thanks for fast reply.
I have already installed docker-engine and docker-composer,
After that i used command "docker -exec .."  as per 4th step
it started application but once opened IP in browser it gives error

**Comment by m-elewa** [comment]
@Akshay-Wagh try to delete this file `/var/www/storage/logs/laravel-2020-07-21.log`
while the application is running and access the website again and see if it fixed

**Comment by m-elewa** [comment]
@Akshay-Wagh also, run this command `sudo usermod -aG docker ${USER}`
it might fix this permission issue

**Comment by m-elewa** [comment]
@Akshay-Wagh if it didn't work try to run it as root like that `sudo docker-compose up -d --build --scale nginx=3`

**Comment by ghost** [comment]
Ok. I will try and let you know

**Comment by ghost** [comment]
Hi, 
sudo docker-compose up -d --build --scale nginx=3
start all docker services but same issue persist.. Here is screenshot of the same 
![Screenshot from 2020-07-21 18-11-43](https://user-images.githubusercontent.com/37117700/88056228-da2db300-cb7d-11ea-9321-37c23260c713.png)


And Application URL https://webandmobileapp.co/

**Comment by m-elewa** [comment]
@Akshay-Wagh please show me the owner and the group of the file `/var/www/storage/logs/laravel-2020-07-21.log` inside the workspace container

**Comment by m-elewa** [comment]
@Akshay-Wagh also, show me the content of the file if it has any

**Comment by ghost** [comment]
file doesn't exist, /var/www/storage/logs/laravel-2020-07-21.log

**Comment by ghost** [comment]
![Screenshot from 2020-07-21 18-41-48](https://user-images.githubusercontent.com/37117700/88058998-ddc33900-cb81-11ea-9f6f-9ecd20276a97.png)
After using command "make setup" in root directory..

**Comment by ghost** [comment]
@m-elewa Thank you very much for your help.

Issue is sorted. 
The problem was "user=laradock", I put root instead laradock in Makefile.
