### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by dsun9** [m-elewa/freelancers-market#3]
Hi,

could you set up a demo website so people can see it?

Thanks.

**Comment by m-elewa** [comment]
@dsun9 We are planning to create a live demo soon.

**Comment by adrianabrahamsun** [comment]
when?

**Comment by m-elewa** [comment]
@adrianabrahamsun There are new updates coming to the project's code, we planning to create the demo website afterward.

**Comment by adrianabrahamsun** [comment]
when? can you give us a deadline?

**Comment by m-elewa** [comment]
@adrianabrahamsun not possible at the moment, because we don't have the server ready.

**Comment by adrianabrahamsun** [comment]
if I lent U a server can you do it? list me the spec...

**Comment by m-elewa** [comment]
@adrianabrahamsun please contact me on mahmoud.elewa.999@gamil.com
to discuss your suggestion. Thanks.

**Comment by adrianabrahamsun** [comment]
your email is invalid. can you contact me instead?....

**Comment by m-elewa** [comment]
@adrianabrahamsun Sorry it's mahmoud.elewa.999@gmail.com

**Comment by m-elewa** [comment]
@dsun9 you can see the demo website that hosted on Azure here http://freelancers-market.ml/
