### ISSUE TITLE
I need help to create an instant to try

### ISSUE THREAD

**Issue by adrianabrahamsun** [m-elewa/freelancers-market#5]
Can you help me to create an instant to try on my server>?

**Comment by m-elewa** [comment]
@adrianabrahamsun Do you have Docker installed and running on your server along with Docker Compose?

**Comment by adrianabrahamsun** [comment]
I am a IT idiot.

**Comment by sfdc8** [comment]
I can provide help on software/web development and sever setup. Please contact 88sfdc@gmail.com
