### ISSUE TITLE
Script php artisan migrate:fresh --seed handling the setup event returned with error code 1

### ISSUE THREAD

**Issue by YuHengKit** [m-elewa/freelancers-market#6]
facing error here. can u help? 

SQLSTATE[HY000] [14] unable to open database file

  at vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:181
    177|         if (file_exists($this->config['storage'].$indexName)) {
    178|             unlink($this->config['storage'].$indexName);
    179|         }
    180|
  > 181|         $this->index = new PDO('sqlite:'.$this->config['storage'].$indexName);
    182|         $this->index->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    183|
    184|         $this->index->exec("CREATE TABLE IF NOT EXISTS wordlist (
    185|                     id INTEGER PRIMARY KEY,

      +53 vendor frames
  54  database/seeds/DatabaseSeeder.php:48
      Illuminate\Support\Facades\Facade::__callStatic()

      +30 vendor frames
  85  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script php artisan migrate:fresh --seed handling the setup event returned with error code 1

**Comment by m-elewa** [comment]
@YuHengKit it's a bug sorry, I'll fix it in the next update.
anyway to fix it do this:
create a directory called "scout-indexes" in storage directory.
or just run this command from the project root directory "mkdir storage/scout-indexes"
